<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6hOvJHQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6hOvJHQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6hOvJHQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6hOvJHQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6hOvJHQ\App_KernelDevDebugContainer([
    'container.build_hash' => '6hOvJHQ',
    'container.build_id' => '8993f9cf',
    'container.build_time' => 1637774401,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6hOvJHQ');
